# Site settings
title: constant.coffee
email: nope@constant.coffee
description: > # this means to ignore newlines until "baseurl:"
  Constant.coffee. Writings about aromatherapy, digital strategies, music and more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://constant.coffee" # the base hostname & protocol for your site
twitter_username: raihan_
github_username:  raihan_

# Build settings
markdown: kramdown
